version: "3.8"
services:
  db:
    container_name: testdrive_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  pgadmin:
    container_name: testdrive_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@radiclescience.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
